package io.github.octaviusframework.jdbc

import io.github.octaviusframework.network.PgStream
import io.github.octaviusframework.query.QueryExecutor
import io.github.octaviusframework.types.TypeRegistry
import io.github.octaviusframework.types.TypeRegistryLoader
import java.sql.*
import java.util.Properties
import java.util.concurrent.Executor

class OctaviusConnection(private val stream: PgStream) : Connection {
    val queryExecutor = QueryExecutor(stream)
    val typeRegistry = TypeRegistry()

    init {
        TypeRegistryLoader.load(typeRegistry, queryExecutor)
    }

    fun reloadTypes() {
        typeRegistry.clearOidMappings()
        TypeRegistryLoader.load(typeRegistry, queryExecutor)
    }

    @Suppress("UNCHECKED_CAST")
    override fun <T> unwrap(iface: Class<T>): T {
        if (iface.isInstance(this)) {
            return this as T
        }
        throw SQLException("Cannot unwrap to ${iface.name}")
    }

    override fun isWrapperFor(iface: Class<*>): Boolean = iface.isInstance(this)

    private fun unsupported(): Nothing = throw SQLFeatureNotSupportedException("This feature is not supported by Octavius JDBC Driver")

    override fun createStatement(): Statement = TODO("Not yet implemented")
    override fun prepareStatement(sql: String?): PreparedStatement = TODO("Not yet implemented")
    override fun prepareCall(sql: String?): CallableStatement = unsupported()
    override fun nativeSQL(sql: String?): String = sql ?: ""
    
    override fun setAutoCommit(autoCommit: Boolean) = TODO("Not yet implemented")
    override fun getAutoCommit(): Boolean = TODO("Not yet implemented")
    override fun commit() = TODO("Not yet implemented")
    override fun rollback() = TODO("Not yet implemented")
    override fun close() = TODO("Not yet implemented")
    override fun isClosed(): Boolean = TODO("Not yet implemented")
    
    override fun getMetaData(): DatabaseMetaData = TODO("Not yet implemented")
    override fun setReadOnly(readOnly: Boolean) = TODO("Not yet implemented")
    override fun isReadOnly(): Boolean = TODO("Not yet implemented")
    override fun setCatalog(catalog: String?) = TODO("Not yet implemented")
    override fun getCatalog(): String = TODO("Not yet implemented")
    override fun setTransactionIsolation(level: Int) = TODO("Not yet implemented")
    override fun getTransactionIsolation(): Int = TODO("Not yet implemented")
    override fun getWarnings(): SQLWarning? = TODO("Not yet implemented")
    override fun clearWarnings() = TODO("Not yet implemented")
    
    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement = unsupported()
    override fun prepareStatement(sql: String?, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement = unsupported()
    override fun prepareCall(sql: String?, resultSetType: Int, resultSetConcurrency: Int): CallableStatement = unsupported()
    
    override fun getTypeMap(): MutableMap<String, Class<*>> = unsupported()
    override fun setTypeMap(map: MutableMap<String, Class<*>>?) = unsupported()
    override fun setHoldability(holdability: Int) = unsupported()
    override fun getHoldability(): Int = unsupported()
    override fun setSavepoint(): Savepoint = unsupported()
    override fun setSavepoint(name: String?): Savepoint = unsupported()
    override fun rollback(savepoint: Savepoint?) = unsupported()
    override fun releaseSavepoint(savepoint: Savepoint?) = unsupported()
    
    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement = unsupported()
    override fun prepareStatement(sql: String?, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): PreparedStatement = unsupported()
    override fun prepareCall(sql: String?, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): CallableStatement = unsupported()
    override fun prepareStatement(sql: String?, autoGeneratedKeys: Int): PreparedStatement = unsupported()
    override fun prepareStatement(sql: String?, columnIndexes: IntArray?): PreparedStatement = unsupported()
    override fun prepareStatement(sql: String?, columnNames: Array<out String>?): PreparedStatement = unsupported()
    
    override fun createClob(): Clob = unsupported()
    override fun createBlob(): Blob = unsupported()
    override fun createNClob(): NClob = unsupported()
    override fun createSQLXML(): SQLXML = unsupported()
    
    override fun isValid(timeout: Int): Boolean = TODO("Not yet implemented")
    override fun setClientInfo(name: String?, value: String?) = unsupported()
    override fun setClientInfo(properties: Properties?) = unsupported()
    override fun getClientInfo(name: String?): String = unsupported()
    override fun getClientInfo(): Properties = Properties()
    
    override fun createArrayOf(typeName: String?, elements: Array<out Any>?): java.sql.Array = unsupported()
    override fun createStruct(typeName: String?, attributes: Array<out Any>?): Struct = unsupported()
    
    override fun setSchema(schema: String?) = TODO("Not yet implemented")
    override fun getSchema(): String = TODO("Not yet implemented")
    
    override fun abort(executor: Executor?) = unsupported()
    override fun setNetworkTimeout(executor: Executor?, milliseconds: Int) = TODO("Not yet implemented")
    override fun getNetworkTimeout(): Int = TODO("Not yet implemented")
}
