package io.github.octaviusframework.driver.jdbc

import io.github.octaviusframework.driver.exception.JdbcExceptionMessage
import io.github.octaviusframework.driver.exception.OctaviusJdbcException
import java.sql.Connection
import java.sql.ResultSet
import java.sql.SQLWarning
import java.sql.Statement

/**
 * A stub implementation of java.sql.Statement.
 * It primarily exists to allow connection pools (such as HikariCP) to execute 
 * `connectionInitSql` or `connectionTestQuery` using standard JDBC calls.
 */
internal class OctaviusStatement(private val connection: OctaviusConnection) : Statement {
    
    private var isClosedFlag = false

    private fun checkClosed() {
        if (isClosedFlag) throw OctaviusJdbcException(JdbcExceptionMessage.STATEMENT_CLOSED)
    }

    override fun execute(sql: String?): Boolean {
        checkClosed()
        if (sql == null) throw OctaviusJdbcException(JdbcExceptionMessage.NULL_SQL)
        connection.queryExecutor.execute(sql)
        return false // Return true only if the first result is a ResultSet
    }

    override fun executeUpdate(sql: String?): Int {
        checkClosed()
        if (sql == null) throw OctaviusJdbcException(JdbcExceptionMessage.NULL_SQL)
        val affected = connection.queryExecutor.update(sql)
        return affected.toInt()
    }

    override fun close() {
        isClosedFlag = true
    }

    override fun isClosed(): Boolean = isClosedFlag

    override fun getConnection(): Connection = connection

    // --- Everything else throws SQLFeatureNotSupportedException ---

    private fun unsupported(): Nothing = throw OctaviusJdbcException(JdbcExceptionMessage.FEATURE_NOT_SUPPORTED)

    override fun <T> unwrap(iface: Class<T>?): T = unsupported()
    override fun isWrapperFor(iface: Class<*>?): Boolean = unsupported()

    override fun executeQuery(sql: String?): ResultSet = unsupported()
    override fun getMaxFieldSize(): Int = unsupported()
    override fun setMaxFieldSize(max: Int) = unsupported()
    override fun getMaxRows(): Int = unsupported()
    override fun setMaxRows(max: Int) = unsupported()
    override fun setEscapeProcessing(enable: Boolean) = unsupported()
    override fun getQueryTimeout(): Int = unsupported()
    override fun setQueryTimeout(seconds: Int) = unsupported()
    override fun cancel() = connection.cancelQuery()
    override fun getWarnings(): SQLWarning? = null
    override fun clearWarnings() {}
    override fun setCursorName(name: String?) = unsupported()
    override fun getResultSet(): ResultSet? = null
    override fun getUpdateCount(): Int = -1
    override fun getMoreResults(): Boolean = false
    override fun setFetchDirection(direction: Int) = unsupported()
    override fun getFetchDirection(): Int = unsupported()
    override fun setFetchSize(rows: Int) = unsupported()
    override fun getFetchSize(): Int = unsupported()
    override fun getResultSetConcurrency(): Int = unsupported()
    override fun getResultSetType(): Int = unsupported()
    override fun addBatch(sql: String?) = unsupported()
    override fun clearBatch() = unsupported()
    override fun executeBatch(): IntArray = unsupported()
    override fun getMoreResults(current: Int): Boolean = false
    override fun getGeneratedKeys(): ResultSet = unsupported()
    override fun executeUpdate(sql: String?, autoGeneratedKeys: Int): Int = unsupported()
    override fun executeUpdate(sql: String?, columnIndexes: IntArray?): Int = unsupported()
    override fun executeUpdate(sql: String?, columnNames: Array<out String>?): Int = unsupported()
    override fun execute(sql: String?, autoGeneratedKeys: Int): Boolean = unsupported()
    override fun execute(sql: String?, columnIndexes: IntArray?): Boolean = unsupported()
    override fun execute(sql: String?, columnNames: Array<out String>?): Boolean = unsupported()
    override fun getResultSetHoldability(): Int = unsupported()
    override fun setPoolable(poolable: Boolean) = unsupported()
    override fun isPoolable(): Boolean = unsupported()
    override fun closeOnCompletion() = unsupported()
    override fun isCloseOnCompletion(): Boolean = unsupported()
}
